### PR TITLE
[#910] Helm patching

### PR DESCRIPTION
**Pull request by mcdoker18**
Moved patching of helm deployment in init section and added the wait parameter.

This closes https://github.com/legion-platform/legion/issues/910

### CODE REVIEW

**Comment by mcdoker18** [comment]
bot, test infra

**Comment by mcdoker18** [comment]
bot, test infra

**Comment by mcdoker18** [comment]
bot, test infra

**Comment by mcdoker18** [comment]
bot, test infra

**Comment by mcdoker18** [comment]
bot, test infra

**Review by kirillmakhonin — APPROVED** [review]

**Review by alexander-semenets — APPROVED** [review]

**Pull request merged**
